Feature/vacancy refactoring
Githance/backend pull request #53
Opened 2023-05-14 10:57 UTC by apfirsov

Переработаны пермишины для проекта и вакансий.
В модели Accsess_level добавлен булево "Право редактирования вакансий",  дающее участнику проекта с данным уровнем доступа право создавать? реадктировать и удалять вакансии на эндпоинтах:
```/api/v1/projects/<pk>/vacancies/```
```/api/v1/vacancies/```

2023-05-14 13:07 UTC, Ridmel reviewed
В дополнение. В данный момент при создании вакансии нет никакого ограничения по правам, лишь бы он был авторизован. Это следует из того, что при POST запросе вызывается у пермишена метод `has_permission`, а не `has_object_permission`, т.к. объекта еще нет. 

Данный функционал (ограничение) можно реализовать через пермишен или непосредственно через сериализатор. Можно, конечно, через вью, но лучше не надо вью утолщать.

Табличка из DRF, где можно контролить разные виды запросов: https://www.django-rest-framework.org/api-guide/permissions/#overview-of-access-restriction-methods

2023-05-14 13:07 UTC, Ridmel commented on apps/participants/models.py
> +    vacancy_editing = models.BooleanField(
Предлагаю для булевых переменных использовать соответствующие имена, которые однозначно указывают на их булево происхождение: `is_`, `has_`, `can_`, `should_` и т.д. В нашем случае подойдет `can_edit_vacancy`. Можно, конечно, редуцировать конкретно в этой модели до голого `edit_vacancy`, подразумевая, что здесь будут только булевы переменные, как сделано, например, в джанго в `auth_permission` модели, но мне больше нравится, когда в любой модели один и тот же принцип нейминга.

2023-05-14 13:07 UTC, Ridmel commented on apps/projects/permissions.py
> +        return getattr(obj, "project", None)
А почему у объекта ведется поиск проекта, если сам объект не проект? В каком корректном рабочем случае такое может быть? На первый взгляд выглядит так, что тут должна выкидываться ошибка, а не пытаться проводить поиск в объекте. 

З.Ы. Увидел причину, описал ниже.

2023-05-14 13:07 UTC, Ridmel commented on apps/projects/permissions.py
> +        if self._is_project_owner(request.user, obj):
Я понял, для чего выше была та конструкция с поиском проекта в объекте, это попытка обобщить для нескольких случаев. Мне этот момент видится неясным, как в самом методе `_get_project()`, так и здесь, поскольку обращение идет семантически в таком виде: `Разрешение._является_ли_владельцем_проекта(пользователь, вакансия)`. Т.е. очень странная комбинация.

Я предлагаю убрать вообще метод `_get_project()` из `ProjectPermission`. А получение проекта из вакансии сделать явно в самом пермишене `IsVacancyEditorOrReadOnly`, тогда все встанет на свои места, а запрос `self._is_project_owner(request.user, project)` будет выглядеть естественно и легко читаться без подкапотной магии.

2023-05-14 13:07 UTC, Ridmel commented on apps/projects/permissions.py
> +        queryset = queryset.filter(
Тут можно одним присвоением переменной, не дублируя `queryset =`. Вполне читаемо получается.

2023-05-14 13:20 UTC, apfirsov commented on apps/projects/permissions.py
> +        queryset = queryset.filter(
black отвратительно форматирует, поэтому разнес)

2023-05-14 13:28 UTC, apfirsov commented on apps/projects/permissions.py
> +        if self._is_project_owner(request.user, obj):
у нас есть два случая проверки права на вакансии:
1) Во вьюсете вакансий, объектом будет сама вакансия
2) Во вьюсете проекта для метода `vacancies()`, который `detail=True`, в связи с чем, объектом будет проект (Проверяем есть ли у пользователя право добавлять вакансии в ПРОЕКТ)
3) При дальнейшей разработке у нас будут еще модели, содержащие проект в атрибутах и ситуация будет повторятся

Поэтому я для DRY сразу вынес в отдельный класс общую для всех этих случаев обработку и реализовал эту логику. 
Выкидывать эксепшин, если это не проект и у объекта нет проекта - да как вариант, пока что сделал логику на возврат `None` с постобработкой по месту вызова

2023-05-14 13:34 UTC, apfirsov commented on apps/projects/permissions.py
> +        return getattr(obj, "project", None)
ответил там же

2023-05-25 09:17 UTC, Ridmel requested changes
При попытке отобразить вакансию в админке выкидывает ошибку. Нужно чтобы `__str__` метод возвращал строку, а сейчас инт. Скорее всего ты хотел сделать `self.profession.name`.

![image](https://github.com/Githance/backend/assets/80767090/9da7ed0c-7bc0-4a9b-8e15-6e99a481243f)

Плюс можно уже убрать 25 строчку в `projects/viewsets.py`  `TODO uncompleted ProjectViewSet`

2023-05-25 09:17 UTC, Ridmel commented on apps/projects/permissions.py
>          if request.method in SAFE_METHODS:
Этот пермишен специфичен для `POST` запроса. Имеет ли смысл указывать случаи с `SAFE_METHODS`?

2023-05-25 09:17 UTC, Ridmel commented on apps/projects/permissions.py
> +        if request.method in SAFE_METHODS:
Аналогичный случай. Нужен ли `SAFE_METHODS`?

2023-05-25 14:59 UTC, apfirsov commented on apps/projects/permissions.py
> +        if request.method in SAFE_METHODS:
Да, тут нужен. У нас есть retrieve obj на `GET /vacancies/<id>/`

2023-05-25 15:02 UTC, apfirsov commented on apps/projects/permissions.py
>          if request.method in SAFE_METHODS:
формально да, safe methods у нас есть только для `has_permission`. Взаимодействие с объектом предполагается только в `POST`, но для целостности можно оставить

2023-05-25 15:13 UTC, Ridmel approved these changes

2023-05-25 15:14 UTC, merged