Bugfix/change telegram name storing and validation
Githance/backend pull request #56
Opened 2023-05-27 13:49 UTC by Ridmel

Имя telegram теперь проверяется только на бэкенде. Пользователь может прописать его как со знаком `@`, так и без. Перед сохранением в БД добавляется этот знак, если он отсутствует. Из БД загружается как есть, т.е. с собакой.

2023-05-27 14:11 UTC, apfirsov reviewed
не понял, почему получилось несколько точек, где добавляем @

2023-05-27 14:11 UTC, apfirsov commented on apps/projects/serializers.py
> +    def validate_telegram(self, value):
немного не понял, мы назначали validate_telegram_name как валиадатор, где делается тоже самое что и здесь. Не лишняя ли эта функция?

2023-05-27 14:11 UTC, apfirsov commented on apps/users/serializers.py
> +    def validate_telegram(self, value):
здесь тот же вопрос

2023-05-27 14:47 UTC, Ridmel commented on apps/projects/serializers.py
> +    def validate_telegram(self, value):
Валидатор модели ничего не возвращает. Его функция - выкинуть ошибку, если что. Нужно еще где-то этот самый знак добавить. Лучше всего подошел валидатор сериализатора. Совсем исключить валидацию при сохранении модели мы не можем, т.к. в модель может попасть эта запись не только через сериализатор, а, например, через админку.

2023-05-27 15:04 UTC, apfirsov commented on apps/projects/serializers.py
> +    def validate_telegram(self, value):
Не понимаю, в 32 строке для поля сериализатора задан валидатор

2023-05-27 15:11 UTC, Ridmel commented on apps/projects/serializers.py
> +    def validate_telegram(self, value):
Я явно задаю это поле в сериализаторе именно с целью, чтобы исключить другие валидаторы (min_ и max_lengh) из процесса валидации, если они прошли путем сериализатора. Иначе происходит двойная валидация (но это ладно) и пользователю выводится два сообщения в случаях, когда он написал слишком короткое имя или слишком длинное.

2023-05-27 22:55 UTC, apfirsov commented on apps/projects/serializers.py
> +    def validate_telegram(self, value):
Продебажил твою ветку. Понял о чем ты говорил тут "Валидатор модели ничего не возвращает. Его функция - выкинуть ошибку, если что. Нужно еще где-то этот самый знак добавить"

При этом мне по-прежнему не нравится то что в разных местах эта история с собачкой, плюс само поле для ТГ используется в нескольких местах и возможно будет еще расширятся.
Вижу такой вариант решения:
Создать класс `TelegramField`, который наследуется от `serializers.CharField`
В этом классе переопределить `to_internal_value() `и добавлять там собачку 1 раз для всех случаев использования.
Потестировал у себя, вот такой вариант не плохо смотрится и в других местах тогда прибавление собачки можно вообще убрать (из админки например можно принимать в строгом формате)

`
class TelegramField(serializers.CharField):

    def to_internal_value(self, data):
        value = super().to_internal_value(data)
        if value.startswith("@"):
            value = "@" + value
        return value
`

2023-05-27 22:55 UTC, apfirsov requested changes
Добавил в комментах предложение по поводу собачек

2023-05-29 20:23 UTC, apfirsov approved these changes
Да, вот так мне нравится.

2023-05-29 20:35 UTC, merged